version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Extensions.Logging.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 5aOb6I5NRP86KkV7nlAJmgyeuXXcrkWjZZZBPCZ7kAnw33ibgSMLdoGph3NMo0Xf
  skip_symbols: true
  on:
    branch: /^(main|dev)$/
